import { GithubClient } from "../tools/githubClient.js";
import { DockerSandbox } from "../tools/dockerSandbox.js";

export interface CompletedFix {
  file: string;
  task: string;
  issue: string;
}

export class PrAgent {
  /**
   * Commits the fixed files from the sandbox to GitHub and creates a Pull Request.
   * Returns the Pull Request URL.
   */
  public static async createPrForFixes(
    repoUrl: string,
    containerName: string,
    fixes: CompletedFix[],
    projectId: string
  ): Promise<string> {
    // Parse GitHub URL into owner/repo format required by GitHub API
    const repo = GithubClient.parseRepo(repoUrl);
    const branchName = `accessguard-fix-${projectId.slice(0, 8)}-${Date.now()}`;
    console.log(`[PRAgent] Creating GitHub branch: ${branchName} for repo: ${repo}`);
    
    // Create branch
    await GithubClient.createBranch(repo, branchName);

    // Commit each modified file
    for (const fix of fixes) {
      console.log(`[PRAgent] Reading fixed file from container: ${fix.file}`);
      const content = await DockerSandbox.readFile(containerName, fix.file);
      
      const commitMessage = `fix(accessibility): ${fix.task.toLowerCase()}`;
      console.log(`[PRAgent] Committing: ${fix.file} to GitHub branch: ${branchName}`);
      await GithubClient.commitFile(repo, branchName, fix.file, content, commitMessage);
    }

    // Compose PR Description
    const prTitle = `AccessGuard: Automated Accessibility and Security Fixes`;
    const prBody = `
## AccessGuard AI-Generated Fixes

AccessGuard detected and automatically resolved the following issues:

${fixes
  .map(
    (fix, idx) => `
### ${idx + 1}. Fix applied to \`${fix.file}\`
* **Task:** ${fix.task}
* **Issue description:** ${fix.issue}
`
  )
  .join("\n")}

---
*Auto-generated by AccessGuard Planner & Fix Agent Graph.*
    `.trim();

    console.log(`[PRAgent] Opening Pull Request...`);
    const prUrl = await GithubClient.createPullRequest(repo, branchName, prTitle, prBody);
    console.log(`[PRAgent] Pull Request created successfully! URL: ${prUrl}`);
    return prUrl;
  }
}
